baseURL = 'https://example.org/'
    title = 'BotC - Lugdunum'
theme = 'ananke'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    locale = 'en-us'
    label = 'English'
    weight = 1
    contentDir = 'content/en'
title = 'BotC - Lugdunum'

  [languages.fr]
    locale = 'fr-fr'
    label = 'Français'
    weight = 2
    contentDir = 'content/fr'
    title = 'BotC - Lugdunum'

[params]
  description = 'BotC - Lugdunum rulebook and character reference'
  body_classes = 'avenir bg-botc-dark'
  background_color_class = 'bg-botc-header'
  text_color = 'botc-text'
  ananke_social = false
  ananke_home_feature = false

[menu]
  [[menu.main]]
    identifier = 'rulebook'
    name = 'Rulebook'
    url = '/en/rulebook/'
    weight = 10
  [[menu.main]]
    identifier = 'characters'
    name = 'Characters'
    url = '/en/characters/'
    weight = 20
  [[menu.main]]
    identifier = 'scenarios'
    name = 'Scenarios'
    url = '/en/scenarios/'
    weight = 30
  [[menu.main]]
    identifier = 'sheets'
    name = 'Sheets'
    url = '/en/sheets/'
    weight = 40
  [[menu.main]]
    identifier = 'toolbox'
    name = 'Toolbox'
    url = '/en/toolbox/'
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.googleAnalytics]
    ID = ''
