baseURL = 'https://example.org/'
    title = 'BotC - Lugdunum'
theme = 'ananke'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    locale = 'en-us'
    label = 'English'
    weight = 1
    contentDir = 'content/en'
    title = 'BotC - Lugdunum'

    [[languages.en.menu.main]]
      identifier = 'rulebook'
      name = 'Rulebook'
      url = '/en/rulebook/'
      weight = 10
    [[languages.en.menu.main]]
      identifier = 'characters'
      name = 'Characters'
      url = '/en/characters/'
      weight = 20
    [[languages.en.menu.main]]
      identifier = 'scenarios'
      name = 'Scenarios'
      url = '/en/scenarios/'
      weight = 30
    [[languages.en.menu.main]]
      identifier = 'sheets'
      name = 'Sheets'
      url = '/en/sheets/'
      weight = 40
    [[languages.en.menu.main]]
      identifier = 'toolbox'
      name = 'Toolbox'
      url = '/en/toolbox/'
      weight = 50

  [languages.fr]
    locale = 'fr-fr'
    label = 'Français'
    weight = 2
    contentDir = 'content/fr'
    title = 'BotC - Lugdunum'

    [[languages.fr.menu.main]]
      identifier = 'rulebook'
      name = 'Règles'
      url = '/fr/rulebook/'
      weight = 10
    [[languages.fr.menu.main]]
      identifier = 'characters'
      name = 'Personnages'
      url = '/fr/characters/'
      weight = 20
    [[languages.fr.menu.main]]
      identifier = 'scenarios'
      name = 'Scénarios'
      url = '/fr/scenarios/'
      weight = 30
    [[languages.fr.menu.main]]
      identifier = 'sheets'
      name = 'Feuilles'
      url = '/fr/sheets/'
      weight = 40

[params]
  description = 'BotC - Lugdunum rulebook and character reference'
  body_classes = 'avenir bg-botc-dark'
  background_color_class = 'bg-botc-header'
  text_color = 'botc-text'
  ananke_social = false
  ananke_home_feature = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.googleAnalytics]
    ID = ''
